USE [APPSOP_BI]
GO

/****** Object:  Table [dbo].[DIM_PRODUTO]    Script Date: 5/1/2020 12:02:08 PM ******/
DROP TABLE [dbo].[DIM_PRODUTO]
GO

/****** Object:  Table [dbo].[DIM_PRODUTO]    Script Date: 5/1/2020 12:02:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DIM_PRODUTO](
	[SKPRODUTO] [int] IDENTITY(1,1) NOT NULL,
	[TSOP_ORDBILITECOD] [nvarchar](255) NULL,
	[TSOP_ORDBILITENOM] [nvarchar](255) NULL,
	[TSOP_ORDBILITEUNI] [nvarchar](10) NULL,
	[TSOP_ORDBILITEFAM] [nvarchar](255) NULL,
	[TSOP_ORDBILITEFAMPAI] [nvarchar](255) NULL,
	[TSOP_ORDBILVALLIQ] [numeric](18, 2) NULL,
	[STATUSREGISTRO] [nvarchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[SKPRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


