
USE [APPSOP_BI]
GO

/****** Object:  Table [dbo].[DIM_CLIENTE]    Script Date: 5/1/2020 10:56:28 AM ******/
DROP TABLE [dbo].[DIM_CLIENTE]
GO

/****** Object:  Table [dbo].[DIM_CLIENTE]    Script Date: 5/1/2020 10:56:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DIM_CLIENTE](
	[SKCLIENTE] [int] IDENTITY(1,1) NOT NULL,
	[IDCLIENTE] [nvarchar](255) NOT NULL,
	[NOME] [nvarchar](100) NULL,
	[ESTADO] [nvarchar](10) NULL,
	[REGIAO] [nvarchar](20) NULL,
	[STATUSREGISTRO] [nvarchar](15) NULL,
PRIMARY KEY CLUSTERED 
(
	[SKCLIENTE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

