USE [APPSOP_BI]
GO

/****** Object:  Table [dbo].[DIM_VENDEDOR]    Script Date: 5/1/2020 11:52:20 AM ******/
DROP TABLE [dbo].[DIM_VENDEDOR]
GO

/****** Object:  Table [dbo].[DIM_VENDEDOR]    Script Date: 5/1/2020 11:52:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DIM_VENDEDOR](
	[SKVENDEDOR] [int] IDENTITY(1,1) NOT NULL,
	[IDVENDEDOR] [int] NULL,
	[NOME] [nvarchar](50) NULL,
	[TSOP_PLANTA] [nvarchar](100) NULL,
	[TSOP_CANAL] [nvarchar](100) NULL,
	[STATUSREGISTRO] [nvarchar](15) NULL,
 CONSTRAINT [PK__DIM_VEND__B87C02A2972147B8] PRIMARY KEY CLUSTERED 
(
	[SKVENDEDOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


