CREATE PROCEDURE [DBO].[PRC_BI_VENDEDOR](@DATA_START DATETIME, @DATA_END DATETIME)
AS
BEGIN

DECLARE @DT_FISCAL DATETIME
DECLARE @MONTH INT
DECLARE @YEAR INT
DECLARE @FIRSTDATE DATETIME
DECLARE @LASTDATE DATETIME

SET @FIRSTDATE = (DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)) 
SET @LASTDATE = DATEADD(D, -1, DATEADD(M, DATEDIFF(M, 0, GETDATE()) + 1, 0))



SET @DT_FISCAL = (SELECT DATEADD(DD,0, DATEDIFF(DD,0, DATEADD( MM,
 -(((12 + DATEPART(M, GETDATE())) - 8)%12), GETDATE() ) 
 - DATEPART(D,DATEADD( MM, -(((12 + DATEPART(M, GETDATE())) - 7)%12),GETDATE()))+1 ) ))

SET @MONTH =  DATEDIFF(MM,@DT_FISCAL,DATEADD(MM,1,GETDATE()))

IF @MONTH > 5
BEGIN
  SELECT  @YEAR = YEAR((SELECT DATEADD(Y,1,GETDATE())))
END
ELSE 
BEGIN
   SELECT   @YEAR = YEAR((SELECT DATEADD(Y,0,GETDATE())))
END

SELECT DISTINCT 
                TSOP_PLANTA = CONVERT(NVARCHAR(100), V.TSOP_ORDBILSITNOM)
		       ,TSOP_CANAL  = CONVERT(NVARCHAR(100), V.TSOP_ORDBILCANNOM)
		       ,TSOP_ORDBILREPNOM = CONVERT(NVARCHAR(50), CASE WHEN (V.TSOP_ORDBILREPNOM = '' OR V.TSOP_ORDBILREPNOM = '-') THEN 'UNKNOW' ELSE  V.TSOP_ORDBILREPNOM END)
			   ,TSIS_USUEML = CONVERT(NVARCHAR(100), X.TSIS_USUEML)
FROM  (
SELECT TSIS_USUNOM = COALESCE(A01.TSIS_USUNOM, B01.TSOP_ORDBILREPNOM)
      ,TSIS_USUEML = COALESCE(A01.TSIS_USUEML,'SOMEBODYSEMAIL@SOMESERVER.COM')
FROM (
       SELECT A01.TSIS_USUNOM
			 ,A01.TSIS_USUEML
	   FROM TSIS_USUARIO A01
	   WHERE A01.TSIS_USUATI = 'S'
         AND A01.TSIS_USUSREP = 'S'
	              ) A01 RIGHT JOIN (

										SELECT B01.TSOP_ORDBILREPNOM
										FROM DBO.VSOP_MONTHS A01 CROSS JOIN DBO.VSOP_CLIENTEBYSALESREP B01
																 LEFT  JOIN DBO.VSOP_ORDERBILLING      C01 ON ( B01.TSOP_ORDBILCLICOD     = C01.TSOP_ORDBILCLICOD
																											AND B01.TSOP_ORDBILCANNOM     = C01.TSOP_ORDBILCANNOM
																											AND A01.YEARDOC               = C01.TSOP_ORDBILYEADOCREQ
																											AND A01.MONTHDOC              = C01.TSOP_ORDBILMONDOCREQ
																											AND C01.TSOP_ORDBILDATDOCREQ >= @FIRSTDATE
																											AND C01.TSOP_ORDBILDATDOCREQ <= @LASTDATE)
										WHERE 1 = 1
										  AND A01.YEARDOC  = @YEAR
										  AND A01.MONTHDOC = @MONTH
										GROUP BY B01.TSOP_ORDBILREPNOM )
														 B01 ON ( A01.TSIS_USUNOM = B01.TSOP_ORDBILREPNOM )
																		) X

																		INNER JOIN  VSOP_ORDERBILLINGFULL V ON V.TSOP_ORDBILREPNOM  = X.TSIS_USUNOM
                                                                     WHERE ((V.TSOP_ORDBILDATDOC > @DATA_START) AND (V.TSOP_ORDBILDATDOC <= @DATA_END))



END