CREATE PROCEDURE PRC_BI_VENDEDOR(@DATA_START DATETIME, @DATA_END DATETIME)
AS
BEGIN
SELECT DISTINCT 
                TSOP_PLANTA = CONVERT(NVARCHAR(100), V.TSOP_ORDBILSITNOM)
		       ,TSOP_CANAL  = CONVERT(NVARCHAR(100), V.TSOP_ORDBILCANNOM)
		       ,TSOP_ORDBILREPNOM = CONVERT(NVARCHAR(50), CASE WHEN (V.TSOP_ORDBILREPNOM = '' OR V.TSOP_ORDBILREPNOM = '-') THEN 'UNKNOW' ELSE  V.TSOP_ORDBILREPNOM END)
FROM VSOP_ORDERBILLINGFULL V
 WHERE (V.TSOP_ORDBILDATDOC > @DATA_START) AND (V.TSOP_ORDBILDATDOC <= @DATA_END)

 END