USE [AppSOP]
GO

/****** Object:  View [dbo].[VW_BI_CLIENTE]    Script Date: 5/1/2020 10:55:29 AM ******/
DROP VIEW [dbo].[VW_BI_CLIENTE]
GO

/****** Object:  View [dbo].[VW_BI_CLIENTE]    Script Date: 5/1/2020 10:55:29 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [DBO].[VW_BI_CLIENTE]
AS
WITH DADOS 
AS
(
SELECT DISTINCT ROW_NUMBER() OVER(PARTITION BY TSOP_ORDBILCLICOD ORDER BY TSOP_ORDBILCLICOD) AS COLUNA, 
				TSOP_ORDBILCLICOD = CONVERT( NVARCHAR(255), VOB.TSOP_ORDBILCLICOD), 
				TSOP_ORDBILCLINOM = CONVERT( NVARCHAR(100), VOB.TSOP_ORDBILCLINOM) , 
				TSOP_ORDBILREGEST = CONVERT( NCHAR(2), VOB.TSOP_ORDBILREGEST), 
				TSOP_ORDBILREG    = CONVERT( NVARCHAR(20), VOB.TSOP_ORDBILREG)

FROM VSOP_ORDERBILLINGFULL VOB
WHERE VOB.TSOP_ORDBILCLICOD <> ''
)
SELECT  TSOP_ORDBILCLICOD, TSOP_ORDBILCLINOM, CASE TSOP_ORDBILREGEST WHEN '' THEN 'XX' ELSE TSOP_ORDBILREGEST END TSOP_ORDBILREGEST, TSOP_ORDBILREG
 FROM DADOS
 WHERE COLUNA  IN
  (SELECT MIN(COLUNA) FROM DADOS
   GROUP BY TSOP_ORDBILCLICOD
   HAVING COUNT(TSOP_ORDBILCLICOD)>1
   )



GO

