
USE [AppSOP]
GO

/****** Object:  View [dbo].[VW_BI_PRODUTO]    Script Date: 5/1/2020 12:01:40 PM ******/
DROP VIEW [dbo].[VW_BI_PRODUTO]
GO

/****** Object:  View [dbo].[VW_BI_PRODUTO]    Script Date: 5/1/2020 12:01:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_BI_PRODUTO]
AS
WITH DADOS 
AS
(
SELECT DISTINCT  ROW_NUMBER() OVER(PARTITION BY TSOP_ORDBILITECOD ORDER BY TSOP_ORDBILITECOD) AS COLUNA, 
TSOP_ORDBILITECOD = convert(nvarchar(255), VOB.TSOP_ORDBILITECOD), 
TSOP_ORDBILITENOM = convert(nvarchar(255),VOB.TSOP_ORDBILITENOM), 
TSOP_ORDBILITEUNI = convert(nvarchar(10),VOB.TSOP_ORDBILITEUNI), 
TSOP_ORDBILITEFAM = convert(nvarchar(255), VOB.TSOP_ORDBILITEFAM),
TSOP_ORDBILITEFAMPAI = convert(nvarchar(255),VOB.TSOP_ORDBILITEFAMPAI),
VOB.TSOP_ORDBILVALLIQ

FROM VSOP_ORDERBILLINGFULL VOB
WHERE VOB.TSOP_ORDBILCLICOD <> ''
)
SELECT  TSOP_ORDBILITECOD, 
        TSOP_ORDBILITENOM, 
		case TSOP_ORDBILITEUNI when '' then 'UNKWON' else TSOP_ORDBILITEUNI end TSOP_ORDBILITEUNI, 
		case TSOP_ORDBILITEFAM when '' then 'UNKWON' else TSOP_ORDBILITEFAM end TSOP_ORDBILITEFAM, 
		case TSOP_ORDBILITEFAMPAI when '' then 'UNKWON' else TSOP_ORDBILITEFAMPAI end TSOP_ORDBILITEFAMPAI,
		TSOP_ORDBILVALLIQ
 FROM DADOS
 WHERE COLUNA  IN
  (SELECT MIN(COLUNA) FROM DADOS
   GROUP BY TSOP_ORDBILITECOD
   HAVING COUNT(TSOP_ORDBILITECOD)>1)

GO

