USE [AppSOP]
GO

/****** Object:  View [dbo].[VW_BI_VENDEDOR]    Script Date: 5/1/2020 11:54:24 AM ******/
DROP VIEW [dbo].[VW_BI_VENDEDOR]
GO

/****** Object:  View [dbo].[VW_BI_VENDEDOR]    Script Date: 5/1/2020 11:54:24 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

   CREATE VIEW [DBO].[VW_BI_VENDEDOR]
   AS
   SELECT R.TSOP_REPCOD  
          ,TSOP_PLANTA = CONVERT(NVARCHAR(100), RC.TSOP_PLANTA)
		  ,TSOP_CANAL  = CONVERT(NVARCHAR(100), RC.TSOP_CANAL)
		  ,TSOP_REPNOM = CONVERT(NVARCHAR(50), R.TSOP_REPNOM)
   FROM TSOP_REPRESENTANTE R
   INNER JOIN TSOP_REPRESENTANTECANAL RC ON RC.TSOP_REPNOM =  R.TSOP_REPNOM
    WHERE R.TSOP_REPNOM NOT IN ('','-')  AND  R.TSOP_REPCOD IN (SELECT MIN(X.TSOP_REPCOD) FROM TSOP_REPRESENTANTE X
            GROUP BY X.TSOP_REPNOM
			HAVING COUNT(X.TSOP_REPNOM) > 1)
GO


